-- Seed dos 14 modos e 124 perguntas do SMI (Inventário de Modos Esquemáticos),
-- conforme Damasceno (2020) / adaptação brasileira via GAAPCC.

insert into public.smi_modes (code, name, category, question_count, description) values
  ('crianca_vulneravel', 'Criança Vulnerável', 'crianca', 10, 'Sentimentos de medo, abandono, tristeza, desamparo, necessidades emocionais não atendidas.'),
  ('crianca_zangada', 'Criança Zangada', 'crianca', 10, 'Percepção de injustiça, causada pelo não atendimento de necessidades emocionais básicas. Isso faz com que o indivíduo se sinta bravo, irritado e, frequentemente, impaciente.'),
  ('crianca_raivosa', 'Criança Raivosa', 'crianca', 10, 'Sentimentos de indignação, enfurecimento e dificuldades de manter o controle sobre as emoções e impulsos.'),
  ('crianca_impulsiva', 'Criança Impulsiva', 'crianca', 9, 'Avalia busca imediata por prazer, baixa tolerância à frustração; desconsideração dos limites e das necessidades alheias.'),
  ('crianca_indisciplinada', 'Criança Indisciplinada', 'crianca', 6, 'Dificuldade de planejamento, procrastinação, baixa constância; desorganização, baixa persistência, dificuldade com regras.'),
  ('crianca_feliz', 'Criança Feliz', 'crianca', 10, 'Este modo é a experiência de se sentir leve e espontâneo, como uma criança amada, protegida e satisfeita, o que ocorre quando as necessidades emocionais básicas estão atendidas.'),
  ('capitulador_complacente', 'Capitulador Complacente', 'enfrentamento_disfuncional', 7, 'Submissão, passividade, dificuldade em defender limites.'),
  ('protetor_desligado', 'Protetor Desligado', 'enfrentamento_disfuncional', 9, 'Desligamento emocional, evitação, entorpecimento afetivo.'),
  ('autoconfortador_desligado', 'Autoconfortador Desligado', 'enfrentamento_disfuncional', 4, 'Uso de comportamentos autoapaziguadores (ex.: comida, compras, internet) para reduzir emoções intensas.'),
  ('autoengrandecedor', 'Autoengrandecedor', 'hipercompensador', 10, 'Este estado descreve o indivíduo que age de forma competitiva, apresentando-se como grandioso, especial e superior aos outros, acreditando ter direitos diferenciados.'),
  ('intimidacao_ataque', 'Intimidação e Ataque', 'hipercompensador', 9, 'O indivíduo adota comportamentos de dominação (como intimidações, ameaças e agressões) por acreditar que esta é a única forma de manter o controle e, assim, evitar ser humilhado, ferido ou controlado pelos outros.'),
  ('pais_punitivos', 'Pais Punitivos', 'pais_internalizados', 10, 'O Modo Pai/Mãe Punitivo é caracterizado por vozes internalizadas que surgem de maneira implacável, trazendo mensagens agressivas, excessivamente críticas e depreciativas.'),
  ('pais_exigentes_criticos', 'Pais Exigentes/Críticos', 'pais_internalizados', 10, 'Este modo é marcado por vozes internalizadas (não psicóticas) que perpetuam padrões de exigência rígidos da infância. Elas emergem rapidamente ao detectar erros, ativando uma hipervigilância focada em eficiência, que, a longo prazo, prejudica a saúde e a felicidade do indivíduo.'),
  ('adulto_saudavel', 'Adulto Saudável', 'adulto_saudavel', 10, 'Este modo é considerado adaptativo por integrar, de forma equilibrada, as respostas às demandas internas e externas. Ele permite ao indivíduo satisfazer suas necessidades emocionais construtivamente, usando compaixão e respeito aos limites.');

insert into public.smi_questions (mode_id, question_number, question_text) values
  ((select id from public.smi_modes where code = 'intimidacao_ataque'), 1, 'Eu exijo respeito ao não permitir que os outros me intimidem ou mandem em mim.'),
  ((select id from public.smi_modes where code = 'crianca_feliz'), 2, 'Eu me sinto amado e aceito.'),
  ((select id from public.smi_modes where code = 'pais_punitivos'), 3, 'Eu não me permito sentir prazer, pois não mereço.'),
  ((select id from public.smi_modes where code = 'crianca_vulneravel'), 4, 'Eu me sinto fundamentalmente inadequado, falho ou defeituoso.'),
  ((select id from public.smi_modes where code = 'pais_punitivos'), 5, 'Eu tenho impulsos de me punir, me machucando (p. ex., me cortando).'),
  ((select id from public.smi_modes where code = 'crianca_vulneravel'), 6, 'Eu me sinto perdido.'),
  ((select id from public.smi_modes where code = 'pais_exigentes_criticos'), 7, 'Eu sou duro comigo mesmo.'),
  ((select id from public.smi_modes where code = 'capitulador_complacente'), 8, 'Eu me esforço muito para agradar outras pessoas; assim, evito conflitos, confrontos ou rejeição.'),
  ((select id from public.smi_modes where code = 'pais_punitivos'), 9, 'Eu não consigo me perdoar.'),
  ((select id from public.smi_modes where code = 'autoengrandecedor'), 10, 'Eu faço coisas para que eu me torne o centro das atenções.'),
  ((select id from public.smi_modes where code = 'autoengrandecedor'), 11, 'Eu fico irritado quando as pessoas não fazem o que eu peço.'),
  ((select id from public.smi_modes where code = 'crianca_impulsiva'), 12, 'Eu tenho dificuldade de controlar meus impulsos.'),
  ((select id from public.smi_modes where code = 'crianca_indisciplinada'), 13, 'Se eu não consigo atingir um objetivo, me frustro facilmente e desisto.'),
  ((select id from public.smi_modes where code = 'crianca_raivosa'), 14, 'Eu tenho acessos de raiva.'),
  ((select id from public.smi_modes where code = 'crianca_impulsiva'), 15, 'Eu ajo de forma impulsiva ou expresso emoções que magoam os outros ou me causam problemas.'),
  ((select id from public.smi_modes where code = 'pais_punitivos'), 16, 'Quando algo ruim acontece, a culpa é minha.'),
  ((select id from public.smi_modes where code = 'crianca_feliz'), 17, 'Eu me sinto contente e tranquilo.'),
  ((select id from public.smi_modes where code = 'capitulador_complacente'), 18, 'Eu mudo o meu jeito de ser dependendo de quem esteja comigo, assim essas pessoas gostarão de mim ou me aprovarão.'),
  ((select id from public.smi_modes where code = 'crianca_feliz'), 19, 'Eu me sinto conectado às outras pessoas.'),
  ((select id from public.smi_modes where code = 'adulto_saudavel'), 20, 'Quando ocorrem problemas, me esforço bastante para resolvê-los eu mesmo.'),
  ((select id from public.smi_modes where code = 'crianca_indisciplinada'), 21, 'Eu não me disciplino para concluir tarefas chatas ou rotineiras.'),
  ((select id from public.smi_modes where code = 'crianca_zangada'), 22, 'Se eu não brigar, as pessoas se aproveitarão de mim ou me ignorarão.'),
  ((select id from public.smi_modes where code = 'pais_exigentes_criticos'), 23, 'Eu preciso cuidar das pessoas à minha volta.'),
  ((select id from public.smi_modes where code = 'intimidacao_ataque'), 24, 'Se você permitir que as outras pessoas façam piadas ou mexam com você, você é um trouxa.'),
  ((select id from public.smi_modes where code = 'crianca_raivosa'), 25, 'Eu agrido as pessoas fisicamente quando estou com raiva delas.'),
  ((select id from public.smi_modes where code = 'crianca_raivosa'), 26, 'Quando eu começo a ficar bravo, muitas vezes não consigo controlar a raiva e perco a cabeça.'),
  ((select id from public.smi_modes where code = 'autoengrandecedor'), 27, 'Para mim, é importante ser o número 1 (p. ex., o mais popular, o mais bem-sucedido, o mais rico, o mais poderoso).'),
  ((select id from public.smi_modes where code = 'protetor_desligado'), 28, 'Eu me sinto indiferente em relação à maioria das coisas.'),
  ((select id from public.smi_modes where code = 'adulto_saudavel'), 29, 'Eu consigo resolver problemas racionalmente, sem deixar que as minhas emoções tomem conta de mim.'),
  ((select id from public.smi_modes where code = 'crianca_indisciplinada'), 30, 'É ridículo planejar como você lidará com as situações.'),
  ((select id from public.smi_modes where code = 'autoengrandecedor'), 31, 'Eu não me contentarei em ficar em segundo lugar.'),
  ((select id from public.smi_modes where code = 'intimidacao_ataque'), 32, 'Atacar é a melhor defesa.'),
  ((select id from public.smi_modes where code = 'protetor_desligado'), 33, 'Eu me sinto frio e emocionalmente afastado das pessoas.'),
  ((select id from public.smi_modes where code = 'protetor_desligado'), 34, 'Eu me sinto desconectado (sem contato comigo mesmo, minhas emoções e com as outras pessoas).'),
  ((select id from public.smi_modes where code = 'crianca_impulsiva'), 35, 'Eu sigo as minhas emoções cegamente.'),
  ((select id from public.smi_modes where code = 'crianca_vulneravel'), 36, 'Eu me sinto desesperado.'),
  ((select id from public.smi_modes where code = 'capitulador_complacente'), 37, 'Eu permito que outras pessoas me critiquem ou me coloquem para baixo.'),
  ((select id from public.smi_modes where code = 'capitulador_complacente'), 38, 'Nas relações, eu deixo a outra pessoa tomar as decisões.'),
  ((select id from public.smi_modes where code = 'protetor_desligado'), 39, 'Eu me sinto distante das outras pessoas.'),
  ((select id from public.smi_modes where code = 'crianca_impulsiva'), 40, 'Eu não penso antes de falar, isso me traz problemas ou machuca as outras pessoas.'),
  ((select id from public.smi_modes where code = 'autoconfortador_desligado'), 41, 'Eu trabalho ou pratico exercícios físicos intensamente para que não precise pensar sobre as coisas que me incomodam.'),
  ((select id from public.smi_modes where code = 'crianca_zangada'), 42, 'Eu estou bravo porque as pessoas estão tentando tirar a minha liberdade ou independência.'),
  ((select id from public.smi_modes where code = 'protetor_desligado'), 43, 'Eu não sinto nada.'),
  ((select id from public.smi_modes where code = 'autoengrandecedor'), 44, 'Eu faço o que eu quero fazer, independentemente dos sentimentos e necessidades dos outros.'),
  ((select id from public.smi_modes where code = 'pais_exigentes_criticos'), 45, 'Eu não me permito relaxar ou me divertir até que tenha terminado tudo o que eu deveria fazer.'),
  ((select id from public.smi_modes where code = 'crianca_raivosa'), 46, 'Eu jogo coisas (longe, no chão, na parede, etc.) quando estou com raiva.'),
  ((select id from public.smi_modes where code = 'crianca_zangada'), 47, 'Eu sinto raiva das outras pessoas.'),
  ((select id from public.smi_modes where code = 'crianca_feliz'), 48, 'Eu me sinto aceito pelas outras pessoas.'),
  ((select id from public.smi_modes where code = 'crianca_zangada'), 49, 'Eu tenho tanta raiva acumulada dentro de mim que preciso extravasá-la.'),
  ((select id from public.smi_modes where code = 'crianca_vulneravel'), 50, 'Eu me sinto só.'),
  ((select id from public.smi_modes where code = 'pais_exigentes_criticos'), 51, 'Eu tento dar o meu melhor em tudo.'),
  ((select id from public.smi_modes where code = 'autoconfortador_desligado'), 52, 'Eu gosto de fazer coisas animadas ou relaxantes para evitar meus sentimentos (p. ex., trabalhar, apostar, comer, fazer compras, atividade sexual, assistir TV).'),
  ((select id from public.smi_modes where code = 'intimidacao_ataque'), 53, 'Igualdade não existe, então é melhor ser superior aos outros.'),
  ((select id from public.smi_modes where code = 'crianca_raivosa'), 54, 'Quando fico bravo, eu frequentemente perco o controle e ameaço as pessoas.'),
  ((select id from public.smi_modes where code = 'capitulador_complacente'), 55, 'Em vez de expressar as minhas próprias necessidades, eu deixo que as pessoas façam as coisas do jeito que preferem.'),
  ((select id from public.smi_modes where code = 'crianca_zangada'), 56, 'Se uma pessoa não concorda comigo, ela está contra mim.'),
  ((select id from public.smi_modes where code = 'autoconfortador_desligado'), 57, 'Eu me esforço para estar sempre ocupado; assim, meus pensamentos e sentimentos incômodos me perturbam menos.'),
  ((select id from public.smi_modes where code = 'pais_punitivos'), 58, 'Quando eu sinto raiva dos outros, me considero uma pessoa má.'),
  ((select id from public.smi_modes where code = 'protetor_desligado'), 59, 'Eu não quero me envolver com as pessoas.'),
  ((select id from public.smi_modes where code = 'crianca_raivosa'), 60, 'Eu sinto tanta raiva que já cheguei a machucar ou matar alguém.'),
  ((select id from public.smi_modes where code = 'crianca_feliz'), 61, 'Eu sinto que tenho bastante estabilidade e segurança na minha vida.'),
  ((select id from public.smi_modes where code = 'adulto_saudavel'), 62, 'Eu sei quando expressar as minhas emoções e quando não as expressar.'),
  ((select id from public.smi_modes where code = 'crianca_zangada'), 63, 'Eu sinto raiva de uma pessoa por ela ter me deixado só ou me abandonado.'),
  ((select id from public.smi_modes where code = 'protetor_desligado'), 64, 'Eu não me sinto conectado às outras pessoas.'),
  ((select id from public.smi_modes where code = 'crianca_indisciplinada'), 65, 'Eu não consigo me disciplinar para fazer coisas que acho desagradáveis, mesmo que eu saiba que são para o meu próprio bem.'),
  ((select id from public.smi_modes where code = 'crianca_impulsiva'), 66, 'Eu desrespeito as regras e depois me arrependo.'),
  ((select id from public.smi_modes where code = 'crianca_vulneravel'), 67, 'Eu me sinto humilhado.'),
  ((select id from public.smi_modes where code = 'crianca_feliz'), 68, 'Eu confio na maioria das pessoas.'),
  ((select id from public.smi_modes where code = 'crianca_impulsiva'), 69, 'Primeiro eu ajo, depois eu penso.'),
  ((select id from public.smi_modes where code = 'crianca_indisciplinada'), 70, 'Eu me entedio facilmente e perco o interesse nas coisas.'),
  ((select id from public.smi_modes where code = 'crianca_vulneravel'), 71, 'Mesmo com pessoas à minha volta, eu me sinto sozinho.'),
  ((select id from public.smi_modes where code = 'pais_punitivos'), 72, 'Eu não me permito fazer coisas agradáveis que as outras pessoas fazem, pois sou uma pessoa má.'),
  ((select id from public.smi_modes where code = 'adulto_saudavel'), 73, 'Eu expresso ou comunico o que necessito sem passar dos limites (p. ex., sem exigir demais dos outros).'),
  ((select id from public.smi_modes where code = 'autoengrandecedor'), 74, 'Eu me sinto especial e melhor do que a maioria das outras pessoas.'),
  ((select id from public.smi_modes where code = 'protetor_desligado'), 75, 'Eu não me importo com nada; nada faz diferença para mim.'),
  ((select id from public.smi_modes where code = 'crianca_zangada'), 76, 'Eu fico bravo quando alguém me diz como devo me sentir ou me comportar.'),
  ((select id from public.smi_modes where code = 'intimidacao_ataque'), 77, 'Se você não dominar os outros, eles dominarão você.'),
  ((select id from public.smi_modes where code = 'crianca_impulsiva'), 78, 'Eu digo o que sinto, ou ajo impulsivamente, sem pensar nas consequências.'),
  ((select id from public.smi_modes where code = 'crianca_zangada'), 79, 'Eu sinto vontade de gritar/brigar com as pessoas pelo jeito como elas me tratam.'),
  ((select id from public.smi_modes where code = 'adulto_saudavel'), 80, 'Eu sou capaz de cuidar de mim mesmo.'),
  ((select id from public.smi_modes where code = 'autoengrandecedor'), 81, 'Eu sou bastante crítico em relação aos outros.'),
  ((select id from public.smi_modes where code = 'pais_exigentes_criticos'), 82, 'Eu estou sob pressão constante para atingir objetivos e dar conta das coisas.'),
  ((select id from public.smi_modes where code = 'pais_exigentes_criticos'), 83, 'Eu estou tentando não cometer erros; caso contrário, irei me criticar fortemente.'),
  ((select id from public.smi_modes where code = 'pais_punitivos'), 84, 'Eu mereço ser punido.'),
  ((select id from public.smi_modes where code = 'adulto_saudavel'), 85, 'Eu posso aprender, crescer e mudar.'),
  ((select id from public.smi_modes where code = 'autoconfortador_desligado'), 86, 'Eu quero me distrair dos pensamentos e sentimentos que possam me deixar chateado.'),
  ((select id from public.smi_modes where code = 'pais_punitivos'), 87, 'Eu estou com raiva de mim mesmo.'),
  ((select id from public.smi_modes where code = 'protetor_desligado'), 88, 'Eu me sinto indiferente e apático.'),
  ((select id from public.smi_modes where code = 'autoengrandecedor'), 89, 'Eu preciso ser o melhor em tudo que faço.'),
  ((select id from public.smi_modes where code = 'pais_exigentes_criticos'), 90, 'Eu sacrifico prazer, saúde e felicidade para satisfazer meus próprios padrões de exigência.'),
  ((select id from public.smi_modes where code = 'autoengrandecedor'), 91, 'Eu exijo bastante das outras pessoas.'),
  ((select id from public.smi_modes where code = 'crianca_raivosa'), 92, 'Se eu fico com raiva, às vezes fico tão fora do controle que agrido fisicamente ou prejudico outras pessoas.'),
  ((select id from public.smi_modes where code = 'intimidacao_ataque'), 93, 'Eu sou inabalável.'),
  ((select id from public.smi_modes where code = 'pais_punitivos'), 94, 'Eu sou uma pessoa má.'),
  ((select id from public.smi_modes where code = 'crianca_feliz'), 95, 'Eu me sinto seguro.'),
  ((select id from public.smi_modes where code = 'crianca_feliz'), 96, 'Eu me sinto ouvido, compreendido, acolhido e aceito.'),
  ((select id from public.smi_modes where code = 'crianca_impulsiva'), 97, 'Para mim, é impossível controlar meus impulsos.'),
  ((select id from public.smi_modes where code = 'crianca_raivosa'), 98, 'Eu destruo coisas quando estou com raiva.'),
  ((select id from public.smi_modes where code = 'intimidacao_ataque'), 99, 'Se você dominar as outras pessoas, nada poderá acontecer com você.'),
  ((select id from public.smi_modes where code = 'capitulador_complacente'), 100, 'Eu ajo de forma passiva mesmo quando não gosto do jeito que as coisas estão.'),
  ((select id from public.smi_modes where code = 'crianca_raivosa'), 101, 'A minha raiva sai do controle.'),
  ((select id from public.smi_modes where code = 'intimidacao_ataque'), 102, 'Eu zombo ou intimido outras pessoas.'),
  ((select id from public.smi_modes where code = 'crianca_zangada'), 103, 'Eu sinto vontade de agredir verbal ou fisicamente alguém pelo que essa pessoa fez para mim.'),
  ((select id from public.smi_modes where code = 'pais_exigentes_criticos'), 104, 'Eu sei que há uma forma "certa" e uma "errada" de fazer as coisas. Eu me esforço para fazer as coisas do jeito certo; caso contrário, eu começo a me criticar.'),
  ((select id from public.smi_modes where code = 'crianca_vulneravel'), 105, 'Eu frequentemente me sinto sozinho no mundo.'),
  ((select id from public.smi_modes where code = 'crianca_vulneravel'), 106, 'Eu me sinto fraco e sem saída.'),
  ((select id from public.smi_modes where code = 'crianca_indisciplinada'), 107, 'Eu sou preguiçoso.'),
  ((select id from public.smi_modes where code = 'capitulador_complacente'), 108, 'Eu posso suportar qualquer coisa que venha das pessoas que são importantes para mim.'),
  ((select id from public.smi_modes where code = 'crianca_zangada'), 109, 'Eu fui traído ou tratado de forma injusta.'),
  ((select id from public.smi_modes where code = 'crianca_impulsiva'), 110, 'Se eu sinto o impulso de fazer alguma coisa, vou e faço.'),
  ((select id from public.smi_modes where code = 'crianca_vulneravel'), 111, 'Eu me sinto deixado de lado ou excluído.'),
  ((select id from public.smi_modes where code = 'intimidacao_ataque'), 112, 'Eu diminuo ou menosprezo os outros.'),
  ((select id from public.smi_modes where code = 'crianca_feliz'), 113, 'Eu me sinto otimista.'),
  ((select id from public.smi_modes where code = 'autoengrandecedor'), 114, 'Eu sinto que não deveria ter que seguir as mesmas regras que as outras pessoas seguem.'),
  ((select id from public.smi_modes where code = 'pais_exigentes_criticos'), 115, 'Neste momento, minha vida se resume a iniciar e concluir tarefas do jeito certo.'),
  ((select id from public.smi_modes where code = 'pais_exigentes_criticos'), 116, 'Eu me cobro para ser mais responsável do que a maioria das outras pessoas.'),
  ((select id from public.smi_modes where code = 'adulto_saudavel'), 117, 'Eu consigo me defender de forma adequada quando me sinto criticado injustamente, maltratado ou quando sinto que tiraram vantagem de mim.'),
  ((select id from public.smi_modes where code = 'pais_punitivos'), 118, 'Eu não mereço pena, ou que os outros sejam compreensivos comigo quando algo de ruim acontece.'),
  ((select id from public.smi_modes where code = 'crianca_vulneravel'), 119, 'Eu sinto que ninguém me ama.'),
  ((select id from public.smi_modes where code = 'adulto_saudavel'), 120, 'Eu sinto que sou uma pessoa fundamentalmente boa.'),
  ((select id from public.smi_modes where code = 'adulto_saudavel'), 121, 'Quando necessário, eu concluo tarefas chatas e rotineiras para que eu conquiste aquilo que eu valorizo.'),
  ((select id from public.smi_modes where code = 'crianca_feliz'), 122, 'Eu me sinto espontâneo e divertido.'),
  ((select id from public.smi_modes where code = 'crianca_raivosa'), 123, 'Às vezes eu fico com tanta raiva que sinto que seria capaz de matar alguém.'),
  ((select id from public.smi_modes where code = 'adulto_saudavel'), 124, 'Eu tenho uma boa noção de quem sou e do que preciso para me deixar feliz.');